services:
  courses_db:
    image: mongo:latest
    container_name: courses_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27019:27017'
    volumes:
      - ./mongo_data:/data/db
